<?php
/**
 * Copyright (c) 2011-2015 VIETMAI Solutions Corporation
 *
 * Released under the MIT license (http://opensource.org/licenses/MIT)
 */
class ParameterController extends _ParameterController
{
    function checkConstraint($model, &$errors) {
       if (trim($model->NAME) == '') {
           $errors[] = sprintf(L_VALIDATION_NOT_EMPTY, L_PARAMETER_NAME);
           return false;
       }
       if (!empty($model->CODE) &&!preg_match('/^[A-Z0-9_]+$/', $model->CODE)) {
           $errors[] = sprintf(L_VALIDATION_CODE, L_CODE);
           return false;
       }
       $_model = new ParameterModel();
       $_model->CODE = $model->CODE;

       if ($model->UUID) {
           $_model->whereAdd('UUID != '.$model->UUID);
       }

       $_model->find();
       if ($_model->N) {
           $errors[] = sprintf(L_VALIDATION_ALREADY_EXISTS, '{'.L_CODE.'}');
           return false;
       }

        return true;
    }

	function syncAction() {
		$model = new ParameterModel();

		$model->selectAdd();
		$model->selectAdd(TABLE_PREFIX.'PARAMETER.*');
		$model->selectAdd(TABLE_PREFIX.'PARAMETER_GROUP.NAME AS GROUP_NAME');

		$model->joinAdd(new ParameterGroupModel(), 'LEFT');
		$model->orderBy(TABLE_PREFIX.'PARAMETER_GROUP.ORDERING');

		$model->find();

		$content = '<?php'."\n";

		$content .= "////////////////////////////////////////////////////////\n";
		$content .= "// Do not edit this file. It is automatically generated\n\n";

		$curgroup = null;
		while ($model->fetch()) {
			if ($model->GROUP_NAME != $curgroup) {
				$curgroup = $model->GROUP_NAME;

				if ($curgroup) {
					$content .= "//________________(".strtoupper($curgroup).")____________________\n\n";
				}
			}

			$content .= "// {$model->NAME}\n";
			$content .= "define('{$model->CODE}', '".addslashes($model->VALUE)."');\n\n";
		}

		$filepath = APPLICATION_DIR.'/../shared/app_constant.php';

		file_put_contents($filepath, $content);

		ContextStack::back(0);
	}
}