<?php
////////////////////////////////////////////////////////
// Do not edit this file. It is automatically generated

//________________(SYSTEM)____________________

// Default currency
define('DEFAULT_CURRENCY_SYMBOL', '$');

// Application name
define('CONFIG_APPLICATION_NAME', 'Extreme Framework');

// CSV separator
define('CSV_SEPARATOR', ',');

// Date format
define('DATE_FORMAT', 'mm-dd-yy');

// Date format (in Smarty)
define('SMARTY_DATE_FORMAT', '%m-%d-%Y');

// Copyright notice
define('COPYRIGHT_NOTICE', 'Copyright &copy; 2011-2015 Extreme Framework. All rights reserved.');

// Default user group
define('DEFAULT_USER_GROUP', '2');

// Positive currency format
define('POSITIVE_CURRENCY_FORMAT', '%s%n');

// Negative currency format
define('NEGATIVE_CURRENCY_FORMAT', '(%s%n)');

// Organization name
define('ORGANIZATION_NAME', 'Extreme Framework');

// Organization name (short)
define('ORGANIZATION_NAME_SHORT', 'Extreme Framework');

// Support name
define('SUPPORT_NAME', 'Extreme Framework');

// Support email
define('SUPPORT_EMAIL', '');

// Default public dashboard
define('DEFAULT_PUBLIC_DASHBOARD', '3');

// GetResponse API key
define('GETRESPONSE_API_KEY', '');

// Use SMTP for sending emails?
define('MAILER_USE_SMTP', '1');

// SMTP host
define('MAILER_SMTP_HOST', 'smtp.gmail.com');

// SMTP port
define('MAILER_SMTP_PORT', '465');

// SMTP username
define('MAILER_SMTP_USERNAME', '');

// SMTP password
define('MAILER_SMTP_PASSWORD', '******');

// Save draft interval (seconds)
define('SAVE_DRAFT_INTERVAL', '10');

// SMTP encryption (tls|ssl)
define('MAILER_SMTP_ENCRYPTION', 'ssl');

//________________(SYNC)____________________

// Cloud sync option
define('CLOUD_SYNC_ENABLED', '1');

